#' Main function of CellTrans: prints transition matrix and predicted equilibrium.
#' 
#' This functions derives and prints the transition probabilities and the predicted equilibrium distribution. The variable input contains the read data from the function readExperimentalData().
#' @param input A list with all necessary data for celltrans which can be generated by readExperimentalData().
#' @keywords transition matrix, Matrix process
#' @export

celltransitions <- function(input) {
 
 
	require(markovchain)
	require(Hmisc)
  require(expm)
trMatrix=calculate_transitionMatrix(input$experimentalData,input$timepoints)
MC <- new("markovchain", states = input$cell_types,
               transitionMatrix = trMatrix,
               name = "Markov Chain")

print("Results of CellTrans")
print("################################")
print(MC)
print("predicted equilibrium distribution")
print(steadyStates(MC))
print("##########################################")
}




