#' Plotting data points and the corresponding predictions of CellTrans.
#' 
#' This function allows to create plots of the predictions of CellTrans together with the experimental data. The variable input contains the read data from readExperimentalData(). One can choose the experiments for which the plot is created.
#' @param input A datalist generated by the function readExperimentaldata().
#' @keywords plot
#' @export
#' @examples
#' celltrans_plot



celltrans_plot <- function(input) {
  timepoints<-dlgList(title="Which timepoints shall be used for the estimation?",multiple=TRUE, choices=input$timepoints)$res  
  
  trMatrix=calculate_transitionMatrix(input$experimentalData,input$timepoints,timepoints)
  



initExp <- as.integer(dlgList(title="Which experiment(s) shall be plotted?", choices=c(1:input$cellnr))$res)
initialcelldistr=input$experimentalData[initExp, ]
maxtime=max(input$timepoints)
colors=rainbow(input$cellnr)
plot(main=paste0("Experiment with initial distribution \n(", paste(input$cell_types,collapse=", "),") = (",paste(initialcelldistr,collapse = ", "),")"),1,1,type="n",xlab=input$timeunits, ylab=paste("fraction of cells"),ylim=c(0,1),xlim=c(0,maxtime),cex.main=0.8)
for (step in 1:maxtime) {
  data=rbind2(initialcelldistr,t(sapply(1:maxtime,
                                        function (step) {initialcelldistr %*% (trMatrix %^% step)})))
}
matplot(add=T,x=c(0:maxtime),y=data,lty=1,type="l",lwd=2,col=colors)
legend("topright",lwd="2", legend=input$cell_types,col=colors)
#plot datapoints

for (i in 1:input$cellnr) {
  #plot initial distribution
  points(0,input$experimentalData[initExp,i],col=colors[i],lwd=2,pch=21,bg=colors[i])
  #plot datapoints
  for (j in 1:length(input$timepoints)) {
    points(input$timepoints[j],input$experimentalData[j*input$cellnr+initExp,i],col=colors[i],lwd=2,pch=21,bg=colors[i])
  }
}
}